version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  sonarqube: syneki/sonarqube@1.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: cimg/postgres:15.1
        environment:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/console_shop
          POSTGRES_DB: console_shop
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: psql < resources/script.sql
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
      