version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  sonarqube: syneki/sonarqube@1.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
      - image: cimg/postgres:15.1
        environment:
          POSTGRES_URL: postgresql://postgres@localhost/console_shop
          POSTGRES_DB: console_shop
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
              psql \
              -d $TEST_DATABASE_URL \
              -c "CREATE DATABASE console_shop
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

  CREATE TABLE categories (
  id   SERIAL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
  );
  
  CREATE TABLE products (
  id            SERIAL,
  name     	  VARCHAR(45) NOT NULL,
  description   VARCHAR(45) NOT NULL,
  price         DECIMAL(10) NOT NULL,
  manufacturer  VARCHAR(45) NOT NULL,
  category_id   INTEGER     NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT category_product_id
  FOREIGN KEY (category_id)
  REFERENCES categories (id)
  ON DELETE CASCADE
  ON UPDATE NO ACTION
  );
  
  INSERT INTO categories (name)
  VALUES
  ('Laptop'),
  ('Tablet'),
  ('Smartphone');
  
  INSERT INTO products (name, description, price, manufacturer, category_id)
  VALUES
  ('Laptop', 'ASUS ROG 751', 1100, 'China', 1),
  ('Laptop', 'ASUS ROG 750', 1300, 'China', 1),
  ('Laptop', 'ASUS ROG 756', 1200, 'China', 1),
  ('Laptop', 'ASUS ROG 755', 900, 'China', 1),
  ('Laptop', 'ASUS ROG 754', 999, 'China', 1),
  ('Laptop', 'ASUS ROG 952', 1500, 'China', 1),
  ('Tablet', 'ASUS ZenPad 751', 800, 'China', 2),
  ('Tablet', 'IPad', 700, 'China', 2),
  ('Tablet', 'Samsung', 900, 'China', 2),
  ('Smartphone', 'Samsung Galaxy', 600, 'South Korea', 3),
  ('Smartphone', 'Xiaomi', 400, 'China', 3),
  ('Smartphone', 'IPhone', 900, 'USA', 3);"
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
      